kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hub-of-hubs-repo
subjects:
- kind: ServiceAccount
  name: hub-of-hubs-repo
  namespace: open-cluster-management
roleRef:
  kind: ClusterRole
  name: hub-of-hubs-repo
  apiGroup: rbac.authorization.k8s.io
